name: CI - Weather Predictor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔧 Build everything tests depend on
      - name: Generate data & train model
        run: |
          python scripts/fetch_and_save.py
          python scripts/feature_engineer.py
          python scripts/train_model.py

      - name: Run pytest
        run: |
          pytest tests/ --disable-warnings -v
